openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/descriptions:
    get:
      summary: 'Show the professional duties.'
      operationId: showTheProfessionalDuties
      description: ''
      parameters:
        -
          in: query
          name: search
          description: 'The search term.'
          example: ''
          required: false
          schema:
            type: string
            description: 'The search term.'
            example: ''
        -
          in: query
          name: grouping
          description: 'A comma seperated order of the grouping. The order must and can only contain the following items: levels, activities, architecture_layers.'
          example: 'architecture_layers,activities,levels'
          required: false
          schema:
            type: string
            description: 'A comma seperated order of the grouping. The order must and can only contain the following items: levels, activities, architecture_layers.'
            example: 'architecture_layers,activities,levels'
        -
          in: query
          name: language
          description: 'The id of the selected language. Defaults to Dutch.'
          example: 1
          required: false
          schema:
            type: integer
            description: 'The id of the selected language. Defaults to Dutch.'
            example: 1
        -
          in: query
          name: level
          description: 'Id of the level.'
          example:
            - 1
          required: false
          schema:
            type: array
            description: 'Id of the level.'
            example:
              - 1
            items:
              type: integer
        -
          in: query
          name: activity
          description: 'Id of the activity.'
          example:
            - 3
          required: false
          schema:
            type: array
            description: 'Id of the activity.'
            example:
              - 3
            items:
              type: integer
        -
          in: query
          name: architecture_layer
          description: 'Id of the architecture layer.'
          example:
            - 2
          required: false
          schema:
            type: array
            description: 'Id of the architecture layer.'
            example:
              - 2
            items:
              type: integer
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The selected language is invalid. (and 3 more errors)'
                  errors:
                    language:
                      - 'The selected language is invalid.'
                    level.0:
                      - 'The selected level.0 is invalid.'
                    activity.0:
                      - 'The selected activity.0 is invalid.'
                    architecture_layer.0:
                      - 'The selected architecture_layer.0 is invalid.'
                properties:
                  message:
                    type: string
                    example: 'The selected language is invalid. (and 3 more errors)'
                  errors:
                    type: object
                    properties:
                      language:
                        type: array
                        example:
                          - 'The selected language is invalid.'
                        items:
                          type: string
                      level.0:
                        type: array
                        example:
                          - 'The selected level.0 is invalid.'
                        items:
                          type: string
                      activity.0:
                        type: array
                        example:
                          - 'The selected activity.0 is invalid.'
                        items:
                          type: string
                      architecture_layer.0:
                        type: array
                        example:
                          - 'The selected architecture_layer.0 is invalid.'
                        items:
                          type: string
      tags:
        - Endpoints
      security: []
  /api/languages:
    get:
      summary: 'Display the supported languages.'
      operationId: displayTheSupportedLanguages
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                properties:
                  data:
                    type: array
                    example: []
      tags:
        - Endpoints
      security: []
  /api/filters:
    get:
      summary: 'Show the possible filters.'
      operationId: showThePossibleFilters
      description: ''
      parameters:
        -
          in: query
          name: language
          description: 'The id of the language.'
          example: 1
          required: false
          schema:
            type: string
            description: 'The id of the language.'
            example: 1
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The selected language is invalid.'
                  errors:
                    language:
                      - 'The selected language is invalid.'
                properties:
                  message:
                    type: string
                    example: 'The selected language is invalid.'
                  errors:
                    type: object
                    properties:
                      language:
                        type: array
                        example:
                          - 'The selected language is invalid.'
                        items:
                          type: string
      tags:
        - Endpoints
      security: []
  /api/professional-skills:
    get:
      summary: 'Show the professional skills descriptions.'
      operationId: showTheProfessionalSkillsDescriptions
      description: ''
      parameters:
        -
          in: query
          name: language
          description: 'The id of the language to use.'
          example: 1
          required: false
          schema:
            type: integer
            description: 'The id of the language to use.'
            example: 1
        -
          in: query
          name: search
          description: 'The search query.'
          example: sustain
          required: false
          schema:
            type: string
            description: 'The search query.'
            example: sustain
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The selected language is invalid.'
                  errors:
                    language:
                      - 'The selected language is invalid.'
                properties:
                  message:
                    type: string
                    example: 'The selected language is invalid.'
                  errors:
                    type: object
                    properties:
                      language:
                        type: array
                        example:
                          - 'The selected language is invalid.'
                        items:
                          type: string
      tags:
        - Endpoints
      security: []
  /api/export:
    get:
      summary: 'Show Retrieve the JSON for the professional duties and professional skills.'
      operationId: showRetrieveTheJSONForTheProfessionalDutiesAndProfessionalSkills
      description: ''
      parameters:
        -
          in: query
          name: search
          description: 'The search term.'
          example: ''
          required: false
          schema:
            type: string
            description: 'The search term.'
            example: ''
        -
          in: query
          name: grouping
          description: 'A comma seperated order of the grouping. The order must and can only contain the following items: levels, activities, architecture_layers.'
          example: 'architecture_layers,activities,levels'
          required: false
          schema:
            type: string
            description: 'A comma seperated order of the grouping. The order must and can only contain the following items: levels, activities, architecture_layers.'
            example: 'architecture_layers,activities,levels'
        -
          in: query
          name: language
          description: 'The id of the selected language. Defaults to Dutch.'
          example: 1
          required: false
          schema:
            type: integer
            description: 'The id of the selected language. Defaults to Dutch.'
            example: 1
        -
          in: query
          name: level
          description: 'Id of the level.'
          example:
            - 1
          required: false
          schema:
            type: array
            description: 'Id of the level.'
            example:
              - 1
            items:
              type: integer
        -
          in: query
          name: activity
          description: 'Id of the activity.'
          example:
            - 3
          required: false
          schema:
            type: array
            description: 'Id of the activity.'
            example:
              - 3
            items:
              type: integer
        -
          in: query
          name: architecture_layer
          description: 'Id of the architecture layer.'
          example:
            - 2
          required: false
          schema:
            type: array
            description: 'Id of the architecture layer.'
            example:
              - 2
            items:
              type: integer
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The selected language is invalid. (and 3 more errors)'
                  errors:
                    language:
                      - 'The selected language is invalid.'
                    level.0:
                      - 'The selected level.0 is invalid.'
                    activity.0:
                      - 'The selected activity.0 is invalid.'
                    architecture_layer.0:
                      - 'The selected architecture_layer.0 is invalid.'
                properties:
                  message:
                    type: string
                    example: 'The selected language is invalid. (and 3 more errors)'
                  errors:
                    type: object
                    properties:
                      language:
                        type: array
                        example:
                          - 'The selected language is invalid.'
                        items:
                          type: string
                      level.0:
                        type: array
                        example:
                          - 'The selected level.0 is invalid.'
                        items:
                          type: string
                      activity.0:
                        type: array
                        example:
                          - 'The selected activity.0 is invalid.'
                        items:
                          type: string
                      architecture_layer.0:
                        type: array
                        example:
                          - 'The selected architecture_layer.0 is invalid.'
                        items:
                          type: string
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
